### ISSUE TITLE
DAppBoard ETL

### ISSUE THREAD

**Issue by adusingi** [jdourlens/awesome-ethereum-analytics#3]
add to tutorial category: 
How to get the #Ethereum blockchain in your #PostgreSQL database easily?
https://github.com/DAppBoard/dappboard-documentation

**Comment by grandsmarquis** [comment]
Thanks for your suggestion @adusingi . Added!

**Comment by adusingi** [comment]
Can you please add the link to "Tutorial" at the beginning in the section "A curated list of projects around Ethereum analytics."? Thank you

**Comment by grandsmarquis** [comment]
done
